services:
  budget:
    image: larsmikki/budget:latest
    container_name: budget
    environment:
      PORT: "3130"
    ports:
      - "3130:3130"
    volumes:
      - budget-data:/app/data
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3130/api/health"]
      interval: 5m
      timeout: 10s
      retries: 3

volumes:
  budget-data:
